### ISSUE TITLE
[Bug]: Stable release reports running nightly 

### ISSUE THREAD

**Issue by jason123santa** [TokTok/qTox#355]
### qTox Version

1.18.0

### Toxcore Version

0.2.20

### Qt Version

6.8.1

### Steps to reproduce

1. Start qTox
2. Go to settings
3. about 

### Observed Behavior

It says that its running an unstable nightly version of qtox even though I installed the latest 1.18.0 release. 

### Expected Behavior

It should say version 1.18.0

### Reproducibility

Always

### Operating System

Linux

### Operating System version/distro/name/etc.

Debian 12

**Comment by iphydf** [comment]
Thanks for reporting. This will be fixed in 1.18.1 by https://github.com/TokTok/qTox/pull/356.

**Comment by iphydf** [comment]
Fixed in [RC 2](https://github.com/TokTok/qTox/releases/tag/v1.18.1-rc.2).

**Comment by 4fury-c3440d8** [comment]
I built release 1.18.1 from xz-tarball. Error persist. qTox running from appimage checks version correctly.

**Comment by iphydf** [comment]
If you build from tarballs, you'll need to set some cmake flags yourself (GIT_DESCRIBE and friends). Maybe we can hard code those in the release tarballs we build next time.

**Comment by 4fury-c3440d8** [comment]
These flags and their descriptions are missing from the `cmake -LA` output.

GIT_VERSION is a hash a commit. GIT_DESCRIBE is a version number. Am I right?
What value should it have GIT_DESCRIBE_EXACT?

**Comment by iphydf** [comment]
https://github.com/TokTok/qTox/actions/runs/12624212845/job/35174169530#step:4:520
```
-- Git version: 307d086ba45ebd3702c4a22cf1f899d4350efdfa
-- Git describe: v1.18.1
-- Git describe exact: v1.18.1
```

**Comment by 4fury-c3440d8** [comment]
OK. Thanks!
